project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jade-y-liang
      - icon: linkedin
        href: https://www.linkedin.com/in/jade-yuqiong-liang/

format:
  html:
    theme: minty
    css: styles.css



